services:
  - type: web
    name: screenwatch-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: JWT_SECRET
        generateValue: true